RunConsoleCommand( "sv_accelerate", 5 )
RunConsoleCommand( "sv_friction", 4 )
RunConsoleCommand( "sv_sticktoground", 0 )
RunConsoleCommand( "sv_gravity", 800 )
RunConsoleCommand( "sv_turbophysics", 1 )