RunConsoleCommand( "sv_accelerate", 7 )
RunConsoleCommand( "sv_airaccelerate", 14 )
RunConsoleCommand( "sv_friction", 6 )
RunConsoleCommand( "sv_sticktoground", 0 )
RunConsoleCommand( "sv_gravity", 800 )
RunConsoleCommand( "sv_turbophysics", 1 )